spring.application.name=application
spring.datasource.url=jdbc:postgresql://localhost:5432/ifa_ats_db
logging.level.org.hibernate.engine.transaction.jta.platform.internal=WARN
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.ai.openai.api-key=none
spring.jpa.properties.hibernate.transaction.jta.platform=org.springframework.boot.orm.jpa.hibernate.SpringJtaPlatform
